### ISSUE TITLE
PCA bug in simpleSeg() function

### ISSUE THREAD

**Issue by ecool50** [SydneyBioX/simpleSeg#18]
When running the simpleSeg() function, leaving the default pca value creates very strange-looking masks.  (see below)
![image](https://github.com/SydneyBioX/simpleSeg/assets/8261982/d01d0cdc-eb82-4d30-8641-c03e9fa82074)

This is fixed by setting `pca = TRUE` (see below)
`masks <- simpleSeg(images,
                   nucleus = c("HH3", "DNA1", "DNA2"),
                   cellBody = "dilate",
                   transform = "sqrt",
                   sizeSelection = 40,
                   discSize = 3,
                   cores = nCores, 
                   pca = TRUE)`
This provides a much better result (see below)
![image](https://github.com/SydneyBioX/simpleSeg/assets/8261982/47b5c764-98e8-4c22-9a79-c93725749b66)

Not sure why this is the case

**Comment by nick-robo** [comment]
We were multiplying the nuclear signal by the nucleus threshold mask in during intensity watershedding. Now it's fixed!
