### ISSUE TITLE
Parallel spelt incorrectly in places

### ISSUE THREAD

**Issue by ellispatrick** [SydneyBioX/simpleSeg#7]

**Comment by anic0077** [comment]
done (I really should learn how to spell)

**Comment by kevinwang09** [comment]
@anic0077, you might find this helpful. When you write a commit message locally prior to `git push`, you can use keywords like "ref #7" to automatically link a commit to the said issue. This creates a track record of your work and a history of development which is useful if the future you are not sure why some codes/comments were in place. 
 
https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message
